config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search/index', to: 'search#index', as: :home
  get 'search/show/:id', to: 'search#show'

  get 'document', to: 'document#index'
  post 'document/create', to: 'document#create'
  get 'moderate/edit/:id', to: 'document#edit'
  post 'moderate/edit/:id', to: 'document#update'

  get 'moderate', to: 'moderate#index'
  delete 'moderate', to: 'document#delete'
  post 'moderate/approve', to: 'document#approve'
  get 'moderate/show_approved', to: 'moderate#show_approved'


  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new
    if user.client?
	  can [:create, :read], Document
	elsif user.admin?
	  can :manage, :all
	else
	  can :read, Document
	end


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/directory.rb
class Directory < ApplicationRecord
  has_many :childs, class_name: "Directory", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Directory"
  has_many :documents
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :directory
  has_and_belongs_to_many :tags
end

app/models/moderate.rb
class Moderate < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles


  belongs_to :resource,
          :polymorphic => true,
		  :optional => true

  validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :tag_category
  has_and_belongs_to_many :documents
end

app/models/tag_category.rb
class TagCategory < ApplicationRecord
  has_many :tags
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

  has_many :documents, dependent: :destroy


  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

end

app/controllers/document_controller.rb
class DocumentController < ApplicationController

	load_and_authorize_resource

    before_action :authenticate_user!

	def index

	end

	def create
		params.permit!
		# @document = Document.new(params.require(:document).permit(:teacher, :subject, :year, :typedoc, :tags0, :tags1))
	 #    @document.file = @document.typedoc+"_"+@document.subject+"_"+@document.teacher+"_"+@document.year.to_s+"_"+Time.now.to_s + Time.now.usec.to_s+".pdf"
		# File.open("db/documents/"+@document.file, 'wb') { |f| f.write( params[:document][:datafile].read ) }
		
		# @document.user = current_user
		# @document.approved = false

		# @tag0nome = params[:document][:tags0]
		# @tag1nome = params[:document][:tags1]
		
		# if not @document.save
		# 	render "create"
		# end

		# if @tag0nome != ""
		# 	# Checar tag antes de aprova-lá
		# 	@document.tags.create(nome: @tag0nome, status: true ) 
		# end

		# if @tag1nome != ""
		# 	# Checar tag antes de aprova-lá
		# 	@document.tags.create(nome: @tag1nome, status: true ) 
		# end	

		redirect_to route_for(:home)
	end
  
	def delete
		@document = Document.find(params[:id])
		File.delete("db/documents/"+@document.file);
		@document.destroy
	end
	
	def approve
		@document = Document.find(params[:id])
		@document.approved = true
		@document.save
	end
	
	def edit
		@document = Document.find(params[:id])
	end
	
	def update
		
		@document = Document.find(params[:id])
		if not @document.update(params[:document].permit(:teacher, :subject, :year, :typedoc))
			render "edit"
		end

		redirect_to "/moderate"
	end
end

app/controllers/moderate_controller.rb
class ModerateController < ApplicationController
	load_and_authorize_resource

    before_action :authenticate_user!

	def index
		@documents = Document.where(approved: false)
	end

	def show_approved
		@documents = Document.where(approved: true)
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 
  def index
    @documents = Document.where(approved: true)
	@current_user = current_user
  end

  def show
    @document = Document.where(id: params[:id])
    if @document.exists?
	  send_file(File.open("db/documents/"+@document[0].file), filename: @document[0].file, type: 'application/pdf', disposition: :inline )
	else
	  render plain: "Documento não encontrado", content_type: "text/plain"
	end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/moderate_helper.rb
module ModerateHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/document/edit.html.erb
<h1>EDITAR DOCUMENTO</h1><br>
<%= form_for :document, :url => { :action => "update" } do |f| %>
	<tag>Professor: </tag> <%= f.text_field :teacher %><br>
	<tag>Disciplina: </tag> <%= f.text_field :subject %><br>
	<tag>Ano: </tag> <%= f.number_field :year %><br>
	<tag>Tipo: </tag> <%= f.text_field :typedoc %><br>
	<br>
	
	<%= submit_tag "Update" %>
<% end %>

app/views/document/index.html.erb
<h1>UPLOAD DO DOCUMENTO</h1><br>
<%= form_for :document, :url => { :action => "create" } do |f| %>

	<!-- <tag>Professor: </tag> <%= f.text_field :teacher %><br>
	<tag>Disciplina: </tag> <%= f.text_field :subject %><br>
	<tag>Ano: </tag> <%= f.number_field :year %><br>
	<tag>Tipo: </tag> <%= f.text_field :typedoc %><br>
	<tag>Arquivo: </tag> <%= f.file_field :datafile %><br>
	<tag>Tags: </tag> 
	<%= f.text_field :tags0 %>
	<%= f.text_field :tags1 %> -->
	<!--<tag>Nome do Documento:</tag> <%= f.text_field :name %><br>
	<tag>Diretorio:</tag> <%= f.number_field :directory_id %><br>-->

	<br>
	
	<%= submit_tag "Create" %>
<% end %>

<%= button_to "Logout", destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0">
    <title>FarolRails</title>
    <link rel="icon" href="<%= asset_path('farol.png') %>">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="farol-nav">
      <div class="container-fluid farol-nav__content">
        <div class="farol-nav__content__header col-xs-2">
          <img class="logo-img" src="<%= asset_path('farol.png') %>">
          <a href="/" class="logo-text"><span>FAROL</span></a>
        </div>
        <div class="farol-nav__content__buttons">
          <div class="farol-nav__content__buttons__item">
            <%= link_to "Login", document_path %>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </nav>
    <div class="farol-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/moderate/index.html.erb
<h1>Moderador</h1>
<br>
<%= link_to "Ver provas aprovadas", controller: "moderate", action: "show_approved" %>
<br>
<h3>Provas não aprovadas:</h3>
<br>
<% @documents.each do |d| %>
	<tag>Professor: </tag> <%= d.teacher %>
	<tag>Disciplina: </tag> <%= d.subject %>
	<tag>Ano: </tag> <%= d.year %>
	<tag>Tipo: </tag> <%= d.typedoc %>
	<tag>Arquivo: </tag> <%= link_to "PDF", controller: "search", action: "show", id: d.id %>
	<br>
	<%= button_to "Editar", {action: "edit", controller: "document", id: d.id }, method: :get %>
	<%= button_to "Deletar", { action: "delete", controller: "document", id: d.id }, method: :delete, data: { confirm: "are you sure?" } %>
	<%= button_to "Aprovar", { action: "approve", controller: "document", id: d.id }, method: :post, data: { confirm: "are you sure?" } %>
	<br>
<% end %>

app/views/moderate/show_approved.html.erb
<h1>Moderador</h1>
<br>
<h3>Provas aprovadas:</h3>
<br>
<% @documents.each do |d| %>
	<tag>Professor: </tag> <%= d.teacher %>
	<tag>Disciplina: </tag> <%= d.subject %>
	<tag>Ano: </tag> <%= d.year %>
	<tag>Tipo: </tag> <%= d.typedoc %>
	<tag>Arquivo: </tag> <%= link_to "PDF", controller: "search", action: "show", id: d.id %>
	<br>
	<%= button_to "Editar", {action: "edit", controller: "document", id: d.id }, method: :get %>
	<%= button_to "Deletar", { action: "delete", controller: "document", id: d.id }, method: :delete, data: { confirm: "are you sure?" } %>
	<br>
<% end %>

app/views/search/index.html.erb
<section class="container">
	<div class="card-box">
		<div class="panel">
			<div class="panel-title">
				<h1 class="m-t-10 header-title">Documentos</h1>
			</div>
			<div class="panel-body">
				<% @documents.each do |d| %>
					<tag>Professor: </tag> <%= d.teacher %>
					<tag>Disciplina: </tag> <%= d.subject %>
					<tag>Ano: </tag> <%= d.year %>
					<tag>Tipo: </tag> <%= d.typedoc %>
					<tag>Arquivo: </tag> <%= link_to "PDF", controller: "search", action: "show", id: d.id %>
					<tag>Tags: </tag> 
					<% d.tags.each do |l| %>
						<%= l.nome %>
					<% end %>	
				<% end %>
			</div>
		</div>
	</div>
</section>